name: Deploy to Git Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies And Generate Build
        run: |
          npm install
          npm run build
          git config user.name "Naveen Kumar Bollepalli"
          git config user.email "bollepallinaveen@gmail.com"
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
